//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillReportsGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BillReportsGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Информация о программе&quot;.
        /// </summary>
        internal static string InfoApp {
            get {
                return ResourceManager.GetString("InfoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of numbers.
        /// </summary>
        internal static string ListOfNumbers {
            get {
                return ResourceManager.GetString("ListOfNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of services.
        /// </summary>
        internal static string ListOfServices {
            get {
                return ResourceManager.GetString("ListOfServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовые файлы (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenDialogTextFiles {
            get {
                return ResourceManager.GetString("OpenDialogTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------.
        /// </summary>
        internal static string RowDashedLines {
            get {
                return ResourceManager.GetString("RowDashedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===================================================.
        /// </summary>
        internal static string RowDozenOfEqualSymbols {
            get {
                return ResourceManager.GetString("RowDozenOfEqualSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный счет для обработки.
        /// </summary>
        internal static string SelectedInvoice {
            get {
                return ResourceManager.GetString("SelectedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрабатываю полученные данные....
        /// </summary>
        internal static string WorkingWithData {
            get {
                return ResourceManager.GetString("WorkingWithData", resourceCulture);
            }
        }
    }
}
