//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNumbersDetailizationReportGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_contract_link
    {
        public int contract_link_id { get; set; }
        public int contract_id { get; set; }
        public Nullable<int> org_unit_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public System.DateTime from_dt { get; set; }
        public Nullable<System.DateTime> till_dt { get; set; }
        public Nullable<int> pay_model_id { get; set; }
    }
}
