//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNumbersDetailizationReportGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_dp_contract_bill_detail_ex
    {
        public int contract_bill_id { get; set; }
        public int contract_id { get; set; }
        public System.DateTime begin_dt { get; set; }
        public System.DateTime end_dt { get; set; }
        public string tariff_package_name { get; set; }
        public Nullable<decimal> contract_total { get; set; }
        public string emp_name { get; set; }
        public string org_unit_name { get; set; }
        public Nullable<int> warning_cnt { get; set; }
        public string provider_cd { get; set; }
        public string account_name { get; set; }
    }
}
