//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNumbersDetailizationReportGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rs_contract_detail
    {
        public int contract_id { get; set; }
        public int account_id { get; set; }
        public string contract_no { get; set; }
        public string phone_no { get; set; }
        public string phone_no_raw { get; set; }
        public string state { get; set; }
        public string descr { get; set; }
        public string account_name { get; set; }
        public Nullable<int> owner_org_unit_id { get; set; }
        public Nullable<int> org_unit_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_position { get; set; }
        public string org_unit_name { get; set; }
        public string org_unit_cd_path { get; set; }
        public string org_unit_cd_path_name { get; set; }
        public Nullable<int> contract_link_id { get; set; }
        public Nullable<System.DateTime> from_dt { get; set; }
        public Nullable<System.DateTime> till_dt { get; set; }
    }
}
